(() => {
const KEY="pokeloop_guildflow_v2";
const roster=[
{id:"bulba",name:"이상해씨",type:"풀",lv:5,maxHp:72,hp:72,atk:15,def:12,pp:0,quick:{name:"덩굴채찍",pow:10,gain:20},strong:{name:"씨폭탄",pow:42,cost:100}},
{id:"char",name:"파이리",type:"불꽃",lv:5,maxHp:64,hp:64,atk:18,def:9,pp:0,quick:{name:"불꽃세례",pow:11,gain:20},strong:{name:"화염바퀴",pow:46,cost:100}},
{id:"squirt",name:"꼬부기",type:"물",lv:5,maxHp:80,hp:80,atk:13,def:16,pp:0,quick:{name:"물대포",pow:9,gain:25},strong:{name:"아쿠아테일",pow:40,cost:100}},
{id:"rattata",name:"꼬렛",type:"노말",lv:4,maxHp:58,hp:58,atk:16,def:8,pp:0,quick:{name:"전광석화",pow:10,gain:25},strong:{name:"필살앞니",pow:38,cost:100}},
{id:"pidgey",name:"구구",type:"비행",lv:4,maxHp:60,hp:60,atk:14,def:9,pp:0,quick:{name:"바람일으키기",pow:10,gain:20},strong:{name:"날개치기",pow:40,cost:100}}
];
const areas=[
{id:"meadow",name:"새싹 들판",difficulty:"쉬움",desc:"초기 포켓몬이 자주 출현하는 평온한 지역.",enemies:[
{name:"꼬렛",icon:"N",hp:52,atk:6,w:28,reward:[2,4]},{name:"구구",icon:"F",hp:46,atk:7,w:24,reward:[2,5]},{name:"캐터피",icon:"B",hp:64,atk:4,w:18,reward:[2,4]},{name:"뿔충이",icon:"B",hp:60,atk:5,w:16,reward:[2,4]},{name:"깨비참",icon:"R",hp:92,atk:10,w:8,reward:[6,10]},{name:"피카츄",icon:"E",hp:110,atk:12,w:6,reward:[8,13]}]},
{id:"forest",name:"깊은 초록 숲",difficulty:"보통",desc:"다수 조우가 늘어나며 탐험대 유지력이 중요해지는 지역.",enemies:[
{name:"파라스",icon:"B",hp:88,atk:9,w:24,reward:[4,7]},{name:"뚜벅쵸",icon:"G",hp:100,atk:8,w:24,reward:[4,7]},{name:"아보",icon:"P",hp:110,atk:11,w:20,reward:[5,8]},{name:"니드런",icon:"P",hp:125,atk:12,w:18,reward:[5,9]},{name:"스라크",icon:"B",hp:180,atk:18,w:8,reward:[12,18]},{name:"피카츄",icon:"E",hp:135,atk:16,w:6,reward:[10,15]}]},
{id:"cliff",name:"바람 깎인 절벽",difficulty:"어려움",desc:"공격적인 비행·바위 포켓몬이 등장하는 상위 지역.",enemies:[
{name:"깨비참",icon:"R",hp:130,atk:16,w:25,reward:[6,10]},{name:"꼬마돌",icon:"R",hp:180,atk:14,w:25,reward:[7,11]},{name:"롱스톤",icon:"R",hp:260,atk:20,w:18,reward:[10,16]},{name:"골뱃",icon:"P",hp:210,atk:22,w:18,reward:[10,16]},{name:"프테라",icon:"R",hp:320,atk:28,w:8,reward:[18,28]},{name:"망나뇽",icon:"D",hp:520,atk:38,w:6,reward:[35,50]}]}
];
const fresh=()=>({resources:{coin:0,food:0,wood:0,stone:0},roster:structuredClone(roster),selectedArea:"meadow",selectedParty:[],run:null,speed:1,log:[],savedAt:Date.now()});
let state=load(),remaining=3000,last=performance.now();
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(!x)return fresh();const f=fresh();return {...f,...x,resources:{...f.resources,...x.resources},roster:Array.isArray(x.roster)?x.roster:f.roster,run:null};}catch{return fresh();}}
function save(msg=false){state.savedAt=Date.now();localStorage.setItem(KEY,JSON.stringify({...state,run:null}));if(msg)addLog("게임을 저장했습니다.","good");render();}
function time(){return new Date().toLocaleTimeString("ko-KR",{hour12:false,hour:"2-digit",minute:"2-digit",second:"2-digit"});}
function addLog(t,k=""){state.log.push({t:time(),m:t,k});if(state.log.length>120)state.log.shift();renderLog();}
function area(){return areas.find(a=>a.id===state.selectedArea)||areas[0];}
function roll(min,max){return Math.floor(Math.random()*(max-min+1))+min;}
function pickEnemy(a){let total=a.enemies.reduce((s,e)=>s+e.w,0),r=Math.random()*total;for(const e of a.enemies){if(r<e.w)return e;r-=e.w;}return a.enemies[0];}
function renderAreas(){const a=area();$("#areaList").innerHTML=areas.map(x=>`<article class="area-card ${x.id===a.id?"active":""}" data-area="${x.id}"><strong>${x.name}</strong><p>${x.desc}</p><div class="area-meta"><span>${x.difficulty}</span><span>출현 ${x.enemies.length}종</span></div></article>`).join("");$("#areaDetail").innerHTML=`<small>SELECTED AREA</small><h3>${a.name}</h3><p>${a.desc}</p><div class="encounter-tags">${a.enemies.map(e=>`<span>${e.name}</span>`).join("")}</div>`;$$(".area-card").forEach(c=>c.onclick=()=>{state.selectedArea=c.dataset.area;render();});}
function renderPicker(){const sel=state.selectedParty;$("#partyCount").textContent=sel.length+" / 4";$("#partyPicker").innerHTML=state.roster.map(p=>{const on=sel.includes(p.id),disabled=!on&&sel.length>=4;return `<article class="pick-card ${on?"selected":""} ${disabled?"disabled":""}" data-poke="${p.id}"><strong>${p.name}</strong><small>Lv.${p.lv} · ${p.type} · HP ${p.maxHp}</small></article>`}).join("");$$(".pick-card").forEach(c=>c.onclick=()=>{if(c.classList.contains("disabled"))return;const id=c.dataset.poke,i=state.selectedParty.indexOf(id);if(i>=0)state.selectedParty.splice(i,1);else if(state.selectedParty.length<4)state.selectedParty.push(id);render();});$("#startExpeditionBtn").disabled=sel.length<1;}
function start(){if(!state.selectedParty.length)return;const party=state.roster.filter(p=>state.selectedParty.includes(p.id)).map(p=>({...structuredClone(p),hp:p.maxHp,pp:0}));state.run={areaId:state.selectedArea,party,room:0,wins:0,coins:0,enemies:[]};state.log=[];remaining=3000;addLog(area().name+" 탐험을 시작했습니다.","good");render();}
function spawnRoom(){const r=state.run,a=areas.find(x=>x.id===r.areaId);r.room++;if(Math.random()<.42){addLog("구역 "+r.room+": 아무것도 발견하지 못했습니다.");if(Math.random()<.18){state.resources.wood++;addLog("나무 +1 획득.","loot");}return;}
let n=1;if(r.room>5&&Math.random()<.3)n=2;if(r.room>12&&Math.random()<.18)n=3;r.enemies=[];for(let i=0;i<n;i++){const base=pickEnemy(a);r.enemies.push({...base,maxHp:base.hp,hp:base.hp});}addLog("구역 "+r.room+": "+r.enemies.map(e=>e.name).join(", ")+" 조우.");}
function aliveParty(){return state.run.party.filter(p=>p.hp>0);}
function aliveEnemies(){return state.run.enemies.filter(e=>e.hp>0);}
function turn(){const r=state.run;if(!r)return;if(!r.enemies.length){spawnRoom();render();return;}const allies=aliveParty(),foes=aliveEnemies();if(!allies.length){finish(true);return;}for(const p of allies){const targets=aliveEnemies();if(!targets.length)break;const e=targets[Math.floor(Math.random()*targets.length)],strong=p.pp>=p.strong.cost,move=strong?p.strong:p.quick,dmg=Math.max(1,Math.round((p.atk*.55+move.pow)*(.9+Math.random()*.2)));if(strong)p.pp-=p.strong.cost;else p.pp=Math.min(200,p.pp+p.quick.gain);e.hp=Math.max(0,e.hp-dmg);addLog(`${p.name}의 ${move.name}! ${e.name}에게 ${dmg} 피해.${strong?" [강공]":""}`,strong?"good":"");}
if(!aliveEnemies().length){let coins=0;r.enemies.forEach(e=>coins+=roll(e.reward[0],e.reward[1]));state.resources.coin+=coins;r.coins+=coins;r.wins++;addLog("전투 승리. 코인 +"+coins,"loot");r.enemies=[];return;}
for(const e of aliveEnemies()){const targets=aliveParty();if(!targets.length)break;const p=targets[Math.floor(Math.random()*targets.length)],dmg=Math.max(1,Math.round((e.atk-p.def*.2)*(.85+Math.random()*.3)));p.hp=Math.max(0,p.hp-dmg);addLog(`${e.name}의 공격! ${p.name}에게 ${dmg} 피해.`,"bad");if(p.hp<=0)addLog(p.name+"이(가) 쓰러졌습니다.","bad");}if(!aliveParty().length)finish(true);}
function finish(wipe=false){if(!state.run)return;addLog(wipe?"탐험대가 전멸했습니다.":"탐험대가 귀환했습니다.",wipe?"bad":"good");state.roster.forEach(p=>{p.hp=p.maxHp;p.pp=0});state.run=null;state.selectedParty=[];save(false);render();}
function renderRun(){const r=state.run;$("#expeditionLobby").classList.toggle("hidden",!!r);$("#expeditionRunning").classList.toggle("hidden",!r);if(!r)return;const a=areas.find(x=>x.id===r.areaId);$("#runAreaName").textContent=a.name;$("#roomCount").textContent=r.room;$("#runWins").textContent=r.wins;$("#runCoins").textContent=r.coins;$("#activeParty").innerHTML=r.party.map(p=>`<article class="member"><div class="member-top"><strong>${p.name}</strong><small>Lv.${p.lv}</small></div><div class="bar hp"><i style="width:${p.hp/p.maxHp*100}%"></i></div><div class="bar pp"><i style="width:${Math.min(100,p.pp)}%"></i></div></article>`).join("");const es=aliveEnemies();$("#encounterTitle").textContent=es.length?("전투 중 · 적 "+es.length+"마리"):"탐색 중";$("#enemyZone").innerHTML=es.length?es.map(e=>`<article class="enemy-card"><div class="icon">${e.icon}</div><strong>${e.name}</strong><small>HP ${e.hp} / ${e.maxHp}</small><div class="bar hp"><i style="width:${e.hp/e.maxHp*100}%"></i></div></article>`).join(""):'<div class="empty-state">다음 구역을 탐색 중입니다.</div>';}
function renderLog(){const el=$("#log");if(!el)return;el.innerHTML=state.log.length?state.log.slice(-60).map(x=>`<div class="log-line ${x.k}"><time>${x.t}</time><span>${x.m}</span></div>`).join(""):'<div class="empty-state">기록 없음</div>';el.scrollTop=el.scrollHeight;}
function renderPokemon(){$("#pokemonList").innerHTML=state.roster.map(p=>`<article class="poke-card"><strong>${p.name}</strong><small>Lv.${p.lv} · ${p.type}<br>HP ${p.maxHp} / 공격 ${p.atk} / 방어 ${p.def}<br>${p.quick.name} / ${p.strong.name}</small></article>`).join("");}
function render(){$("#coin").textContent=state.resources.coin;$("#food").textContent=state.resources.food;$("#wood").textContent=state.resources.wood;$("#stone").textContent=state.resources.stone;renderAreas();renderPicker();renderRun();renderLog();renderPokemon();}
function bind(){$$(".nav").forEach(b=>b.onclick=()=>{if(state.run&&b.dataset.view!=="expedition")return;$$(".nav").forEach(x=>x.classList.remove("active"));$$(".view").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#view-"+b.dataset.view).classList.add("active");});$("#startExpeditionBtn").onclick=start;$("#returnBtn").onclick=()=>finish(false);$("#saveBtn").onclick=()=>save(true);$("#resetBtn").onclick=()=>{if(confirm("모든 저장 데이터를 초기화할까요?")){localStorage.removeItem(KEY);state=fresh();remaining=3000;render();}};$("#clearLogBtn").onclick=()=>{state.log=[];renderLog();};$$(".speed").forEach(b=>b.onclick=()=>{$$(".speed").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.speed=Number(b.dataset.speed);$("#speedText").textContent=b.dataset.speed+"x";});}
function loop(now){const d=Math.min(100,now-last);last=now;if(state.run){remaining-=d*state.speed;if(remaining<=0){turn();remaining+=3000;}$("#nextAction").textContent=(Math.max(0,remaining)/1000).toFixed(1)+"초";}requestAnimationFrame(loop);}
bind();render();requestAnimationFrame(loop);window.addEventListener("beforeunload",()=>save(false));
})();